### ISSUE TITLE
Morning Session Peer to Peer Code Review ( Yan, Ichsan, Fatima)

### ISSUE THREAD

**Issue by HtetWaiYan7191** [ichsansandy/webpack-todo-list-microverse#5]
### Ichsansandy ToDoList Agree Feedback 
You did  a great job so far 👍 
Nice Design 👍 💯 
Kindly consider to replace your array declaration todoList by using a sing line of code like this: 
`let todoList = JSON.parse(localStorage.getItem('todolist')) || [];` (Fatima) 💯

**Comment by batoolfatima2135** [comment]
You did a great job so far 👍 , But there is always a room for improvement 
I noticed your array declaration in `index.js`
![Capture](https://github.com/ichsansandy/webpack-todo-list-microverse/assets/61277612/282a97d0-a32a-4bb9-8fc0-9599c239e214)
It can get better and these few lines can be replaced by a single line of code like this:
`let todoList = JSON.parse(localStorage.getItem('todolist')) || [];`
